@include('frontend-layouts.main')

<div class="rev-slider">
</div>
<div id="content" class="site-content">
    <div class="container">
        <div class="inner-wrapper">    
            <div id="primary" class="content-area">
                <main id="main" class="site-main" role="main">
                    <article id="post-1556" class="post-1556 page type-page status-publish hentry">
                        <header class="entry-header">
                              <h1 class="entry-title">Gallery</h1>    
                          </header><!-- .entry-header -->
                        @foreach($galleryFolder as $galleryFolders)
                    
                        <div class="col-md-4" style="border: solid;">
                           
                            <div class="row">
                                <a href="{{route('gallery_image_show',$galleryFolders->id)}}">
                                <div>
                                
                                @foreach($galleryFolders->gallery_image as $imageName)
                                @if($imageName->gallery_image)
                                <img src="{{asset($imageName->gallery_image !=null ? $imageName->gallery_image: 'storage/admin/student_demo.png')}}" style="width: 400px; height: 300px; border: solid;">
                                @break;

                                @else
                                <img src="" style="width: 400px; height: 300px; border: solid;">
                                @endif
                                @endforeach
                                </div>
                                </a>
                            </div>
                           
                             <h4>
                                <a class='ngg-album-desc' title='{{$galleryFolders->folder_name}}'href='{{route('gallery_image_show',$galleryFolders->id)}}'style="max-width: 320px">{{$galleryFolders->folder_name}}</a>
                            </h4>
                          
                        </div>
           
                    @endforeach
                    </article><!-- #post-## -->         
                </main><!-- #main -->
            </div><!-- #primary -->
        </div><!-- .inner-wrapper -->
    </div><!-- .container -->
</div><!-- #content -->
    
@include('frontend-layouts.footer')

<!--Generated by Endurance Page Cache-->