<option value="0" selected="">Select Bank</option>
<option value="Allahabad Bank - Retail">Allahabad Bank - Retail</option>
<option value="Andhra Bank">Andhra Bank</option>
<option value="Axis Bank">Axis Bank</option>
<option value="Bandan Bank">Bandan Bank</option>
<option value="Bank of India">Bank of India</option>
<option value="Bank of Baroda">Bank of Baroda</option>
<option value="Bank of Maharashtra">Bank of Maharashtra</option>
<option value="Canara Bank DebitCard">Canara Bank DebitCard</option>
<option value="Canara Bank NetBanking">Canara Bank NetBanking</option>
<option value="Catholic Syrian Bank">Catholic Syrian Bank</option>
<option value="Central Bank of India">Central Bank of India</option>
<option value="City Bank">City Bank</option>
<option value="City Union Bank">City Union Bank</option>
<option value="Corporation Bank">Corporation Bank</option>
<option value="DCB BANK Business">DCB BANK Business</option>
<option value="DCB BANK Personal">DCB BANK Personal</option>
<option value="Delhi Nagrik Sehkari Bank">Delhi Nagrik Sehkari Bank</option>
<option value="Deutsche Bank">Deutsche Bank</option>
<option value="Dhanlaxmi Bank">Dhanlaxmi Bank</option>
<option value="Fedral Bank">Fedral Bank</option>
<option value="HDFC Bank">HDFC Bank</option>
<option value="ICICI Bank">ICICI Bank</option>
<option value="IDBI Bank">IDBI Bank</option>
<option value="IDFC Bank">IDFC Bank</option>
<option value="Indian Bank">Indian Bank</option>
<option value="Indian Overseas Bank">Indian Overseas Bank</option>
<option value="Indusind Bank">Indusind Bank</option>
<option value="Jammu and Kashmir Bank">Jammu and Kashmir Bank</option>
<option value="Kahtri Bank">Kahtri Bank</option>
<option value="Karnataka Bank">Karnataka Bank</option>
<option value="Karur Vysya Bank">Karur Vysya Bank</option>
<option value="Kotak Mahindra Bank">Kotak Mahindra Bank</option>
<option value="Lakshmi Vilas Bank NetBanking">Lakshmi Vilas Bank NetBanking</option>
<option value="ORIENTAL BANK OF COMMERCE">ORIENTAL BANK OF COMMERCE</option>
<option value="Post Office">Post Office</option>
<option value="Punjab and Sind Bank">Punjab and Sind Bank</option>
<option value="Punjab National Bank Retail">Punjab National Bank Retail</option>
<option value="SaraSwat Bank">SaraSwat Bank</option>
<option value="Rakhsha Bank">Rakhsha Bank</option>
<option value="Ramgarhia">Ramgarhia</option>
<option value="RBL Bank">RBL Bank</option>
<option value="RBS Bank">RBS Bank</option>
<option value="South Indian Bank">South Indian Bank</option>
<option value="State Bank of Bikaner and Jaipur">State Bank of Bikaner and Jaipur</option>
<option value="State Bank of Hyderabad">State Bank of Hyderabad</option>
<option value="State Bank of India">State Bank of India</option>
<option value="State Bank of Patiala">State Bank of Patiala</option>
<option value="Syndicate Bank">Syndicate Bank</option>
<option value="Tamilnad Mercantile Bank">Tamilnad Mercantile Bank</option>
<option value="The Kangra CO-OP Bank">The Kangra CO-OP Bank</option>
<option value="UCO Bank">UCO Bank</option>
<option value="Union Bank">Union Bank</option>
<option value="United Bank of India">United Bank of India</option>
<option value="Vijaya Bank">Vijaya Bank</option>
<option value="Yes Bank">Yes Bank</option>
<option value="Dena Bank">Dena Bank</option>
<option value="HSBC">HSBC</option>
<option value="The Vaish Co-operative New Bank Ltd">The Vaish Co-operative New Bank Ltd</option>
<option value="Standard Chartered Bank">Standard Chartered Bank</option>
<option value="Delhi State co-operative Bank">Delhi State co-operative Bank</option>
<option value="The Hongkong and Shanghai Banking Corporation Ltd.">The Hongkong and Shanghai Banking Corporation Ltd.</option>
<option value="The Citizen co-operative Bank Lts.">The Citizen co-operative Bank Lts.</option>
<option value="Citizen co-operative Bank Ltd.">Citizen co-operative Bank Ltd.</option>
<option value="State Bank of MysoreState Bank of Mysore">State Bank of MysoreState Bank of Mysore</option>
<option value="Other">Other</option>